In [19]:
import numpy as np
data = np.random.randn(100, 4)


cov_matrix = np.cov(data, rowvar=False)


eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)

sorted_indices = np.argsort(eigenvalues)[::-1]
sorted_eigenvalues = eigenvalues[sorted_indices]
sorted_eigenvectors = eigenvectors[:, sorted_indices]

print("Sorted Eigenvalues:")
print(sorted_eigenvalues)
print("\nSorted Eigenvectors:")
print(sorted_eigenvectors)


# now selecting 2 coloumns 
main_vector=sorted_eigenvectors[:2]

Sorted Eigenvalues:
[1.45495268 1.19382483 1.03354145 0.79936167]

Sorted Eigenvectors:
[[ 0.26976258  0.49089794  0.63273654  0.53468853]
 [ 0.7670108  -0.05439382 -0.55418431  0.31877187]
 [-0.53643183  0.47593414 -0.52646262  0.45668884]
 [-0.22619346 -0.72769995  0.12394083  0.63555328]]


In [28]:
main_vector=sorted_eigenvectors[:,:2]

In [54]:
data_centered = data - np.mean(data, axis=0)

In [55]:
np.dot(data_centered,main_vector)

array([[ 0.10234999, -0.49175255],
       [ 1.20204506,  1.50540628],
       [-1.03106694,  1.00761708],
       [ 0.3877169 , -0.87538437],
       [ 0.62529423,  0.13952284],
       [-0.83828678, -1.47353773],
       [ 1.1858643 , -0.16659509],
       [ 0.83725484, -0.88100863],
       [-1.44136669,  0.74145673],
       [-0.37138637, -0.68011298],
       [-0.13085872,  0.46669273],
       [-1.18085786, -1.29954551],
       [ 0.27177461, -0.785641  ],
       [ 1.43968081,  0.96125243],
       [-0.98463328,  1.97036379],
       [ 0.48394373, -0.68984472],
       [ 0.6393164 ,  0.17032484],
       [-0.02657802, -2.56671126],
       [ 0.17147846, -1.06926249],
       [ 0.75743617,  0.29751588],
       [ 0.4626046 ,  0.38578241],
       [-0.54568334, -0.03868716],
       [ 0.06230324,  1.95484114],
       [ 0.38790953, -1.11772955],
       [-0.56706158, -0.40509273],
       [-0.50639796, -0.43722825],
       [ 1.01152963, -0.15905848],
       [-1.3274475 , -1.30445294],
       [ 0.30527198,

In [25]:
from sklearn.decomposition import PCA

In [26]:
pca=PCA(n_components=2)

In [27]:
pca.fit_transform(data)

array([[-0.10234999,  0.49175255],
       [-1.20204506, -1.50540628],
       [ 1.03106694, -1.00761708],
       [-0.3877169 ,  0.87538437],
       [-0.62529423, -0.13952284],
       [ 0.83828678,  1.47353773],
       [-1.1858643 ,  0.16659509],
       [-0.83725484,  0.88100863],
       [ 1.44136669, -0.74145673],
       [ 0.37138637,  0.68011298],
       [ 0.13085872, -0.46669273],
       [ 1.18085786,  1.29954551],
       [-0.27177461,  0.785641  ],
       [-1.43968081, -0.96125243],
       [ 0.98463328, -1.97036379],
       [-0.48394373,  0.68984472],
       [-0.6393164 , -0.17032484],
       [ 0.02657802,  2.56671126],
       [-0.17147846,  1.06926249],
       [-0.75743617, -0.29751588],
       [-0.4626046 , -0.38578241],
       [ 0.54568334,  0.03868716],
       [-0.06230324, -1.95484114],
       [-0.38790953,  1.11772955],
       [ 0.56706158,  0.40509273],
       [ 0.50639796,  0.43722825],
       [-1.01152963,  0.15905848],
       [ 1.3274475 ,  1.30445294],
       [-0.30527198,

In [31]:
pca.components_

array([[-0.26976258, -0.7670108 ,  0.53643183,  0.22619346],
       [-0.49089794,  0.05439382, -0.47593414,  0.72769995]])

In [35]:
sorted_eigenvectors[:,:2]

array([[ 0.26976258,  0.49089794],
       [ 0.7670108 , -0.05439382],
       [-0.53643183,  0.47593414],
       [-0.22619346, -0.72769995]])

In [40]:
#Svd

u,singular,v_t=np.linalg.svd(data)

In [38]:
eigenvalues.argsort()[::-1]

array([0, 1, 2, 3], dtype=int64)

array([[ 0.26976258,  0.53468853,  0.49089794,  0.63273654],
       [ 0.7670108 ,  0.31877187, -0.05439382, -0.55418431],
       [-0.53643183,  0.45668884,  0.47593414, -0.52646262],
       [-0.22619346,  0.63555328, -0.72769995,  0.12394083]])

In [49]:
pca.components_

array([[-0.26976258, -0.7670108 ,  0.53643183,  0.22619346],
       [-0.49089794,  0.05439382, -0.47593414,  0.72769995]])

In [50]:
pca.explained_variance_

array([1.45495268, 1.19382483])

In [48]:
v_t.T[:,:2]

array([[-0.26247976, -0.49421866],
       [-0.7662366 ,  0.04066297],
       [ 0.54499068, -0.47098497],
       [ 0.21672793,  0.72956672]])

In [46]:
np.dot(data,v_t.T[:,:2])

array([[-0.04163097,  0.43500821],
       [-1.113033  , -1.57424011],
       [ 1.1136009 , -1.04731124],
       [-0.33190413,  0.81432035],
       [-0.55545344, -0.2025714 ],
       [ 0.88338944,  1.43426042],
       [-1.11856799,  0.09455797],
       [-0.77529328,  0.80328104],
       [ 1.52342663, -0.78176565],
       [ 0.43377382,  0.62406221],
       [ 0.20459309, -0.51672681],
       [ 1.22975912,  1.26332526],
       [-0.21311529,  0.72373942],
       [-1.35271494, -1.0441116 ],
       [ 1.08227978, -2.01042877],
       [-0.42457343,  0.62665528],
       [-0.57234684, -0.22776228],
       [ 0.05867537,  2.51133488],
       [-0.1168889 ,  1.01015135],
       [-0.68491955, -0.36278213],
       [-0.38902467, -0.44706906],
       [ 0.61228203, -0.00693665],
       [ 0.03419732, -2.01136957],
       [-0.33814971,  1.0621552 ],
       [ 0.62801201,  0.36036152],
       [ 0.56863151,  0.38916588],
       [-0.94695176,  0.09211809],
       [ 1.37465366,  1.27318865],
       [-0.23758896,

In [53]:
singular

array([12.02093563, 10.88550627, 10.11577538,  8.89797532])