In [1]:
import numpy as np
from sklearn.decomposition import PCA

# Example dataset with two variables: Height and Weight
data = np.array([[165, 60], [170, 65], [175, 70], [180, 75], [185, 80]])

# Compute the covariance matrix
covariance_matrix = np.cov(data, rowvar=False)

print("Covariance Matrix:")
print(covariance_matrix)

# Perform PCA
pca = PCA(n_components=2)
transformed_data = pca.fit_transform(data)

print("Transformed Data:")
print(transformed_data)

# Interpret the principal components
print("Principal Components:")
print(pca.components_)


Covariance Matrix:
[[62.5 62.5]
 [62.5 62.5]]
Transformed Data:
[[ 14.14213562  -0.        ]
 [  7.07106781   0.        ]
 [ -0.           0.        ]
 [ -7.07106781   0.        ]
 [-14.14213562   0.        ]]
Principal Components:
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]


In [2]:
import numpy as np
from sklearn.decomposition import PCA

# Example data
height = [160, 170, 155, 180, 175]
weight = [60, 65, 55, 70, 68]

# Construct the dataset
data = np.array([height, weight]).T

# Create and fit the PCA model
pca = PCA(n_components=1)
pca.fit(data)

# Transform the data using the PCA model
transformed_data = pca.transform(data)

# Retrieve the principal components
principal_components = pca.components_

# Calculate the variance explained by the principal component
explained_variance_ratio = pca.explained_variance_ratio_

# Print the original data and transformed data
print("Original Data:")
print(data)
print()
print("Transformed Data (Retained information in first principal component):")
print(transformed_data)
print()
print("Principal Components (Weighted combination of height and weight):")
print(principal_components)
print()
print("Explained Variance Ratio:")
print(explained_variance_ratio)


Original Data:
[[160  60]
 [170  65]
 [155  55]
 [180  70]
 [175  68]]

Transformed Data (Retained information in first principal component):
[[  8.72200373]
 [ -2.43343872]
 [ 15.56441391]
 [-13.58888118]
 [ -8.26409774]]

Principal Components (Weighted combination of height and weight):
[[-0.86260646 -0.50587558]]

Explained Variance Ratio:
[0.99654516]


In [8]:
np.dot(np.array([[1,3],[0,2]]),np.array([1,1]))

array([4, 2])

In [11]:
np.array([[1,3],[0,2]])

array([[1., 3.],
       [0., 2.]])

In [24]:
import numpy as np
 

# Define the Hadamard matrix
H = np.array([[5, 2],
              [3, 3]])

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(H)

# Print the eigenvalues and eigenvectors
for i in range(len(eigenvalues)):
    eigenvalue = eigenvalues[i]
    eigenvector = eigenvectors[:, i]
    print("Eigenvalue:", eigenvalue)
    print("Eigenvector:", eigenvector)
    print()

Eigenvalue: 6.645751311064591
Eigenvector: [0.7721779 0.6354064]

Eigenvalue: 1.3542486889354095
Eigenvector: [-0.48096517  0.8767397 ]



In [26]:
A = np.array([[2, -1],
              [4, 3]])

In [7]:
import numpy as np
from sklearn.preprocessing import StandardScaler 
# Sample data
data = np.array([[160, 60, 25],
                 [170, 65, 30],
                 [155, 55, 28],
                 [175, 70, 35],
                 [180, 75, 40]])

# Apply stdandarlization or mean centering 
std=StandardScaler()
data_std=std.fit_transform(data)


# Calculating the Cov-matrix
cov_matrix = np.cov(data_std, rowvar=False)

# Featching diagonal elements of covariance matrix that is variance
variance_matrix = np.diag(cov_matrix)

# Calculating the eigenvectors and eigenvalues of the covariance matrix
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)

# Sort eigenvalues and eigenvectors in descending order
eigenvalue_indices = np.argsort(eigenvalues)[::-1]
eigenvalues = eigenvalues[eigenvalue_indices]
eigenvectors = eigenvectors[:, eigenvalue_indices]

# Perform the transformation using eigenvectors
transformed_data = np.dot(data, eigenvectors)

# Calculate the first two principal components (PC1 and PC2)
pc1 = transformed_data[:, 0]
pc2 = transformed_data[:, 1]


print("Covariance matrix:")
print(cov_matrix)
print("\nVariance matrix:")
print(variance_matrix)
print("\nEigenvectors:")
print(eigenvectors)
print("\nEigenvalues:")
print(eigenvalues)
print("\nPC1:")
print(pc1)
print("\nPC2:")
print(pc2)


Covariance matrix:
[[1.25       1.23905088 1.12111641]
 [1.23905088 1.25       1.13102338]
 [1.12111641 1.13102338 1.25      ]]

Variance matrix:
[1.25 1.25 1.25]

Eigenvectors:
[[-0.58285814 -0.42615995 -0.69185554]
 [-0.58442598 -0.3716999   0.72130816]
 [-0.56455528  0.82475868 -0.03241063]]

Eigenvalues:
[3.57829505 0.16098305 0.0107219 ]

PC1:
[-142.43674285 -154.01023053 -138.29398811 -162.66942753 -171.32862452]

PC2:
[-69.86861853 -71.86492409 -63.40504325 -71.73042991 -71.59593573]
