# Gradient descent 

Gradient descent is an optimization algorithm used to iteratively update the parameters of a model in order to minimize a given cost function. The goal is to find the set of parameters that results in the lowest possible value of the cost function. The algorithm works by computing the gradient of the cost function with respect to the parameters and updating the parameters in the direction of the negative gradient. By repeating this process iteratively, the algorithm can converge towards the minimum of the cost function, which corresponds to the optimal set of parameters for the model.

In [3]:
import numpy as np

# Define the dataset
package = np.array([5, 6, 7, 8, 9, 10, 11, 12])
cgpa = np.array([7, 7.5, 7.8, 8, 8.2, 8.5, 8.8, 9])

In [2]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [3]:
#spliting our datset 

X_train, X_test, y_train, y_test =train_test_split(package,cgpa, test_size=0.2, random_state=42)

In [7]:
lr=LinearRegression()
lr.fit(cgpa.reshape(-1,1),package.reshape(-1,1))


In [61]:
print(lr.coef_)
print(lr.intercept_)

[[3.63057325]]
[-20.90764331]


In [53]:
m=lr.intercept_

In [54]:
class Gdregressor:
    def __init__(self,intercept,learning_rate,epchs):
        self.m=3.63057325
        self.b=intercept
        self.lr=learning_rate
        self.epochs=epchs

    def fit(self,x,y):
        # calculating the the b using the gd(gradient descent)
            
        for i in range (self.epochs):
            loss_slope=-2*(np.sum(y-self.m*x.ravel()-self.b))
            self.b=self.b-self.lr*loss_slope
            print(self.b)
        print(self.b)    


In [65]:
d=Gdregressor(20,0.1,100)

In [66]:
d.fit(cgpa,package)

-45.45222932
-6.180891727999992
-29.743694283200004
-15.606012750079994
-24.088621669952
-18.999056318028796
-22.05279552918272
-20.220552002490365
-21.31989811850578
-20.66029044889653
-21.05605505066208
-20.81859628960275
-20.961071546238347
-20.875586392256988
-20.926877484645804
-20.896102829212516
-20.91456762247249
-20.903488746516505
-20.910136072090094
-20.90614767674594
-20.908540713952434
-20.90710489162854
-20.907966385022874
-20.907449488986273
-20.907759626608232
-20.90757354403506
-20.907685193578963
-20.90761820385262
-20.907658397688426
-20.907634281386944
-20.90764875116783
-20.9076400692993
-20.907645278420418
-20.907642152947748
-20.90764402823135
-20.907642903061188
-20.907643578163285
-20.907643173102027
-20.907643416138782
-20.90764327031673
-20.90764335780996
-20.90764330531402
-20.907643336811585
-20.907643317913045
-20.90764332925217
-20.907643322448695
-20.90764332653078
-20.90764332408153
-20.90764332555108
-20.907643324669348
-20.90764332519839
-20.907643324

-- full fleged 

In [1]:
from sklearn.datasets import make_regression

In [4]:
X,y = make_regression(n_samples=100, n_features=1, n_informative=1, n_targets=1,noise=20,random_state=13)

In [5]:
X_train,X_test,y_train,y__test = train_test_split(X,y,test_size=0.2,random_state=2)

In [8]:
lr.fit(X_train,y_train)

LinearRegression()

In [9]:
lr.coef_

array([28.12597332])

In [10]:
lr.intercept_

-2.2710144261783825

In [11]:
lr.predict(X_test)

array([ 21.09901593,  18.03495551,  18.23747414,  -8.10292651,
        15.72634513,  58.21059953, -15.03324179, -11.33105581,
       -15.81005402,  -8.8082183 , -23.57512364,  14.78144416,
        12.70150681, -23.8893975 , -22.30769518, -16.670531  ,
        24.52827391, -16.98551717,  -3.88916883, -12.01966768])

In [21]:
y_pred = lr.predict(X_test)
from sklearn.metrics import r2_score
r2_score(y__test,y_pred)

0.6345158782661012

In [12]:
y__test

array([  5.63079459,  46.35423956,   6.33015059,  12.48703995,
         6.69670792,  62.8216706 , -19.08818775, -29.39129264,
       -28.68867308, -18.96087356,  -2.40222151,  12.47602642,
         2.54005098, -23.46558518, -34.31988063,   6.09015466,
        20.43721216,   4.38924069, -18.93533099, -10.21709104])

# GDregressor function from scratch

In [13]:
class Gdregressor:
    def __init__(self,m,intercept,learning_rate,epchs):
        self.m=m
        self.b=intercept
        self.lr=learning_rate
        self.epochs=epchs

    def fit(self,x,y):
        # calculating the the b using the gd(gradient descent)
            
        for i in range (self.epochs):
            loss_slope_b=-2*(np.sum(y-self.m*x.ravel()-self.b))
            loss_slope_m=-2*(np.sum((y-self.m*x.ravel()-self.b)*x.ravel()))

            self.b=self.b-self.lr*loss_slope_b
            self.m=self.m-self.lr*loss_slope_m
            
        print(self.b,self.m)  
    def predict(self,x):
           return self.m*x+self.b 


In [14]:
d=Gdregressor(100,-120,0.001,100)

In [15]:
d.fit(X_train,y_train)

-2.2710234077993587 28.12598618006269


In [16]:
Y_pred=d.predict(X_test)

In [17]:
from sklearn.metrics import r2_score

In [22]:
r2_score(y__test,Y_pred)

0.634515826773629