# Simple Linear regresion 

In [27]:
# import important Library 
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression


In [24]:
# Define the number of data points
n_samples = 100

# Create a random dataset with a single feature X and a target variable y
np.random.seed(10)
X = np.random.randn(n_samples)
y = 2*X + 1 + 0.5*np.random.randn(n_samples)

# Print the first 5 rows of the dataset
print("Dataset:")
print(np.concatenate((X.reshape((-1, 1)), y.reshape((-1, 1))), axis=1)[:5])

Dataset:
[[ 1.3315865   3.72191084]
 [ 0.71527897  1.4768295 ]
 [-1.54540029 -2.55225522]
 [-0.00838385  1.21810802]
 [ 0.62133597  2.17048857]]


In [65]:
class mera_sr:

    def __init__(self):
        self.m=None
        self.b=None
    def fit(self,X_train,Y_train):
        X_mean = X_train.mean()
        Y_mean = Y_train.mean()
        self.m = ((X_train - X_mean) * (Y_train - Y_mean)).sum() / ((X_train - X_mean) ** 2).sum()
        self.b = Y_mean - self.m * X_mean
    def predict(self,x_test):
        Y=self.m*x_test+self.b 
        return Y   

            

#### using sklearn library 


In [31]:
#split the data 
X_train, X_test, y_train, y_test = train_test_split(X.reshape(-1, 1), y.reshape(-1, 1), test_size=0.2, random_state=3)

In [29]:
# Create a LinearRegression object
model = LinearRegression()

In [32]:
model.fit(X_train,y_train)

LinearRegression()

In [44]:
model.predict(X_test.reshape(-1,1))[0]

array([-0.4582175])

In [45]:
y_test[0]

array([-0.56932084])

--using mera function 

In [66]:
model1=mera_sr()

In [67]:
model1.fit(X_train,y_train)

In [73]:
print(model1.predict(X_test.reshape(-1,1))[0])

[-0.4582175]


In [74]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [76]:
y_pred = model.predict(X_test)

In [78]:
# Calculate the MSE, MAE, and RMSE metrics
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
rmse = mean_squared_error(y_test, y_pred, squared=False)
print("MSE:", mse)
print("MAE:", mae)
print("RMSE:", rmse)

MSE: 0.39105238203905146
MAE: 0.4852122664166652
RMSE: 0.6253418121627975


In [80]:
r2_score(y_test, y_pred)

0.933903727702756

In [117]:
r2=1-((y_pred - y_test) ** 2).sum()/((y_test - y_test.mean()) ** 2).sum()

In [101]:
r2

0.933903727702756

In [118]:
n=100
p=1
R2_adjusted = 1 - (1 - r2) * (n - 1) / (n - p - 1)

In [120]:
(1 - r2) * (n - 1) / (n - p - 1)

0.06677072405537916

In [119]:
R2_adjusted

0.9332292759446208

In [121]:

# Generate some random data with a linear relationship between X and y
np.random.seed(123)
X = np.random.rand(100, 1)
y = 2*X + np.random.randn(100, 1)

# Fit a linear regression model with one predictor (X)
model1 = LinearRegression().fit(X, y)
y_pred1 = model1.predict(X)
r2_1 = r2_score(y, y_pred1)
print(f"R-squared with one predictor: {r2_1}")

# Add a second predictor (a random noise variable)
X2 = np.concatenate((X, np.random.randn(100, 1)), axis=1)
model2 = LinearRegression().fit(X2, y)
y_pred2 = model2.predict(X2)
r2_2 = r2_score(y, y_pred2)
print(f"R-squared with two predictors: {r2_2}")

R-squared with one predictor: 0.1585895610243382
R-squared with two predictors: 0.15912073870515409


In [115]:
# Calculate adjusted R-squared for both models
n = len(y)
k1 = 1  # one predictor in the first model
k2 = 2  # two predictors in the second model
adj_r2_1 = 1 - ((1 - r2_1) * (n - 1) / (n - k1 - 1))
adj_r2_2 = 1 - ((1 - r2_2) * (n - 1) / (n - k2 - 1))

print(f"Adjusted R-squared with one predictor: {adj_r2_1}")
print(f"Adjusted R-squared with two predictors: {adj_r2_2}")

Adjusted R-squared with one predictor: 0.15000374021846408
Adjusted R-squared with two predictors: 0.14178302197742532
