In [26]:
import numpy as np
from sklearn.linear_model import Ridge
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

# Example data
X = np.array([[2, 4, 6], [4, 6, 8], [10, 12, 14]])
y = np.array([10, 20, 30])

# Splitting the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Ridge regression with cross-validation
ridge = Ridge()
ridge.fit(X_train, y_train)

# Predict on the test set
y_pred = ridge.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)
print("Ridge Coefficients:", ridge.coef_)
print("Ridge Intercept:", ridge.intercept_)


Mean Squared Error: 46.48760330578515
Ridge Coefficients: [0.54545455 0.54545455 0.54545455]
Ridge Intercept: 10.272727272727273


In [23]:
np.linalg.inv(X.T@X+0.1*np.identity(X.shape[1]))

array([[ 1.81920922, -3.31298564,  1.55481951],
       [-3.31298564,  6.66980811, -3.34739814],
       [ 1.55481951, -3.34739814,  1.75038421]])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
X.T@X+0.1*np.identity(X.shape[1])

array([[120.1, 152. , 184. ],
       [152. , 196.1, 240. ],
       [184. , 240. , 296.1]])

In [36]:
import plotly.express as px

In [37]:
x=np.random.randint(1,10,100)

In [38]:
y=np.linspace(1,10,100)

In [39]:
px.scatter(x=x,y=y)